baseURL = 'https://institutocambacica.com'
languageCode = 'pt-br'
title = 'Instituto Cambacica de Audiência'
theme = 'typo'

[params]
  description = 'Este site mostra dados de comparação de audiência entre os principais canais do Youtube'
  author = 'Instituto Cambacica de Audiência'
  homeCollection = 'posts'
  homeCollectionTitle = 'Posts Recentes'
  #homeIntroTitle = 'Instituto Cambacica de Audiência'
  homeIntroContent = 'Aqui você não só se informa. Você verifica a audiência.'
  paginationSize = 10
  
  [[params.menu]]
    name = 'sobre'
    url = '/sobre/'
  
  [[params.menu]]
    name = 'github'
    url = 'https://github.com/institutocambacica'
    newTab = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
